config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :number_of_guests, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..10 }
  validates :price_per_night, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flats, only: [:show]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def set_flats
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1 class="title">All our flats (<%= @flats.count %>)</h1>
</div>
<div class="container">
  <div class="grid">
    <% @flats.each do |flat| %>
      <div class="card border">
        <div class="card-header">
          <div class="card-address">
            <h3><%= flat.name %></h2>
            <p><%= flat.address %></p>
          </div>
          <div class="card-icons">
            <span><i class="fas fa-users"></i> <%= flat.number_of_guests %></span>
            &nbsp;
            <span><i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></span>
          </div>
        </div>
        <div class="card-footer border-top">
          <%= link_to "More info", flat_path(flat) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2">
      <h1 class="title">Add a new Flat</h1>
      <%= simple_form_for (@flat) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :number_of_guests, collection: 1..10, selected: 1 %>
        <%= f.input :price_per_night %>
        <%= f.submit "Add new flat", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1 class="title"><%= @flat.name %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "Simple Airbnb", flats_path %>
    <%= link_to new_flat_path do %>
      <div class="btn btn-primary">
        <i class="fas fa-plus"></i> Add a flat
      </div>
    <% end %>
  </div>

  <body>
    <%= yield %>
  </body>

</html>